

export const regionData =[
    {
        id:'region1',
        name:"Qoraqolpog'iston"
    },
    {
        id:'region2',
        name:"Xorazm"
    },
    {
        id:'region3',
        name:"Navoiy",
        tooltipId:'tooltip3'
    },
    {
        id:'region4',
        name:"Buxoro"
    },
    {
        id:'region5',
        name:"Samarqand"
    },
    {
        id:'region6',
        name:"Jizzax"
    },
    {
        id:'region7',
        name:"Qashqadaryo"
    },
    {
        id:'region8',
        name:"Surxandaryo"
    },
    {
        id:'region9',
        name:"Tashkent"
    },
    {
        id:'region10',
        name:"Farg'ona"
    },
    {
        id:'region11',
        name:"Andijon"
    },
    {
        id:'region12',
        name:"Sirdaryo"
    },
    {
        id:'region13',
        name:"Namangan"
    },
]