

export const regionData =[
    {
        id:'region1',
        name:"Qoraqolpog'iston",
        tooltipId:'tooltip_1'
    },
    {
        id:'region2',
        name:"Xorazm",
        tooltipId:'tooltip_2'
    },
    {
        id:'region3',
        name:"Navoiy",
        tooltipId:'tooltip_3'
    },
    {
        id:'region4',
        name:"Buxoro",
        tooltipId:'tooltip_4'
    },
    {
        id:'region5',
        name:"Samarqand",
        tooltipId:'tooltip_5'
    },
    {
        id:'region6',
        name:"Jizzax",
        tooltipId:'tooltip_6'
    },
    {
        id:'region7',
        name:"Qashqadaryo",
        tooltipId:'tooltip_7'
    },
    {
        id:'region8',
        name:"Surxandaryo",
        tooltipId:'tooltip_8'
    },
    {
        id:'region9',
        name:"Tashkent",
        tooltipId:'tooltip_9',
    },
    {
        id:'region10',
        name:"Farg'ona",
        tooltipId:'tooltip_10',
    },
    {
        id:'region11',
        name:"Andijon",
        tooltipId:'tooltip_11',
    },
    {
        id:'region12',
        name:"Sirdaryo",
        tooltipId:'tooltip_12',
    },
    {
        id:'region13',
        name:"Namangan",
        tooltipId:'tooltip_13',
    },
]